### ISSUE TITLE
PHPUnit not work

### ISSUE THREAD

**Issue by event15** [q2a/question2answer#804]
Hello, 
I did everything as described on this page: https://docs.question2answer.org/contribute/unit-tests/
Unfortunately, I can't run these tests:
```
phpunit --bootstrap qa-tests/autoload.php qa-tests
PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /data/projekty/forum/qa-tests/AppUsersTest.php:5
Stack trace:
#0 phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php(46): include_once()
#1 phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php(37): PHPUnit\Util\FileLoader::load('/data/projekty/...')
#2 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(267): PHPUnit\Util\FileLoader::checkAndLoad('/data/projekty/...')
#3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(340): PHPUnit\Framework\TestSuite->addTestFile('/data/projekty/...')
#4 phar:///usr/local/bin/phpunit/phpunit/Runner/BaseTestRunner.php(81): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(78): PHPUnit\Runner\BaseTestRunner->getTest('/data/projekty/...', Array)
#6 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(66): PHPUnit\TextUI\Command->run(Array, true)
#7 /usr/local/bin/phpunit(718): PHPUnit\Text in /data/projekty/forum/qa-tests/AppUsersTest.php on line 5
```

**Comment by svivian** [comment]
Which version of PHPUnit are you using? You need v4.8 to run our tests.
